export const COMPANY_CATEGORIES = [
  "Vše", "Založení firmy", "Účetnictví", "Daně", "DPH", "Datová schránka", "Úřady", "Zaměstnanci", "Obchodní rejstřík", "Smlouvy", "Banka a cashflow", "GDPR a data", "IT a bezpečnost", "Domény a předplatná", "Firemní auta a majetek",
] as const;

export type CompanyCategory = (typeof COMPANY_CATEGORIES)[number];
export type ObligationSeverity = "critical" | "important" | "routine";
export type ObligationStatus = "open" | "in-progress" | "done";
export type CompanyObligation = {
  id: string; title: string; description: string; category: Exclude<CompanyCategory, "Vše">; deadline: string; severity: ObligationSeverity; status: ObligationStatus; source?: string; verifiedAt?: string; isLegal: boolean;
};

export const COMPANY_OBLIGATIONS: CompanyObligation[] = [
  { id: "tax-registration", title: "Přihlásit s.r.o. k dani z příjmů právnických osob", description: "Po vzniku společnosti ověřit registraci u finančního úřadu.", category: "Založení firmy", deadline: "Do 15 dnů od vzniku", severity: "critical", status: "open", source: "Finanční správa", isLegal: true },
  { id: "accounting", title: "Nastavit účetnictví a předávání dokladů účetní", description: "Domluvit systém pro účtenky, faktury, banku a pravidelný export dokladů.", category: "Účetnictví", deadline: "Při založení firmy", severity: "important", status: "in-progress", isLegal: false },
  { id: "monthly-documents", title: "Odevzdat účetní všechny doklady za minulý měsíc", description: "Faktury přijaté i vydané, účtenky, bankovní výpisy a smlouvy.", category: "Účetnictví", deadline: "Každý měsíc", severity: "important", status: "open", isLegal: false },
  { id: "closing", title: "Připravit účetní závěrku", description: "Zkontrolovat podklady, inventury a uzávěrkové operace s účetní.", category: "Účetnictví", deadline: "Po skončení účetního období", severity: "important", status: "open", source: "Zákon o účetnictví", isLegal: true },
  { id: "corporate-tax-return", title: "Podat daňové přiznání k dani z příjmů právnických osob", description: "Standardně počítat s lhůtou 3 měsíce, případně 4 nebo 6 měsíců podle situace.", category: "Daně", deadline: "3 / 4 / 6 měsíců po období", severity: "critical", status: "open", source: "Finanční správa", isLegal: true },
  { id: "pay-tax", title: "Zaplatit vypočtenou daň", description: "Prověřit variabilní symbol a připsání platby na účet finančního úřadu.", category: "Daně", deadline: "Ve lhůtě pro přiznání", severity: "critical", status: "open", isLegal: true },
  { id: "vat-foreign", title: "Nákup zahraničních služeb: prověřit identifikovanou osobu k DPH", description: "OpenAI, Google, Meta, AWS, Figma nebo jiná služba může založit povinnost registrace.", category: "DPH", deadline: "Při každém nákupu ze zahraničí", severity: "critical", status: "open", source: "Finanční správa", isLegal: true },
  { id: "vat-identified", title: "Při vzniku postavení identifikované osoby hlídat registraci", description: "Přihlášku podat do 15 dnů od rozhodné skutečnosti.", category: "DPH", deadline: "Do 15 dnů od vzniku", severity: "critical", status: "open", source: "Finanční správa", isLegal: true },
  { id: "vat-turnover", title: "Hlídání obratu pro povinnou registraci k DPH", description: "Pro aktuální pravidla počítat obrat za kalendářní rok a sledovat hranice 2 000 000 Kč a 2 536 500 Kč.", category: "DPH", deadline: "Průběžně každý měsíc", severity: "critical", status: "in-progress", source: "Finanční správa", isLegal: true },
  { id: "vat-application", title: "Po překročení hranice podat přihlášku k registraci DPH", description: "Hlídání lhůty 10 pracovních dnů od rozhodné skutečnosti.", category: "DPH", deadline: "Do 10 pracovních dnů", severity: "critical", status: "open", source: "Finanční správa", isLegal: true },
  { id: "data-box", title: "Zkontrolovat, že má firma funkční datovou schránku", description: "Přihlásit se a ověřit, že do schránky mají přístup správné osoby.", category: "Datová schránka", deadline: "Co nejdříve po založení", severity: "critical", status: "done", verifiedAt: "18. 8. 2026", source: "datoveschranky.info", isLegal: true },
  { id: "data-notifications", title: "Nastavit notifikace z datové schránky", description: "Přidat e-mailové notifikace a určit zodpovědnou osobu za kontrolu.", category: "Datová schránka", deadline: "Při založení firmy", severity: "important", status: "done", verifiedAt: "18. 8. 2026", isLegal: false },
  { id: "data-delivery", title: "Nezapomenout na fikci doručení datové zprávy", description: "Nepřečtená datová zpráva může být po 10 dnech považována za doručenou.", category: "Datová schránka", deadline: "Kontrola každý pracovní den", severity: "critical", status: "open", source: "Zákon č. 300/2008 Sb.", isLegal: true },
  { id: "authorities", title: "Zkontrolovat registrace a místní příslušnost úřadů", description: "Finanční úřad, ČSSZ, zdravotní pojišťovny a případné oborové úřady.", category: "Úřady", deadline: "Při změně situace", severity: "important", status: "open", isLegal: true },
  { id: "first-employee", title: "Ověřit povinnosti před přijetím prvního zaměstnance", description: "Registrace, BOZP, pracovnělékařské služby a nastavení interních procesů.", category: "Zaměstnanci", deadline: "Před prvním nástupem", severity: "important", status: "open", isLegal: true },
  { id: "payroll", title: "Nastavit mzdovou agendu při přijetí prvního zaměstnance", description: "Určit zpracovatele mezd, termíny a předávání podkladů.", category: "Zaměstnanci", deadline: "Před prvním nástupem", severity: "important", status: "open", isLegal: false },
  { id: "probation", title: "Hlídání pracovních smluv a konců zkušebních dob", description: "Mít přehled o dodatcích, úvazcích a termínech všech spolupracovníků.", category: "Zaměstnanci", deadline: "Průběžně", severity: "important", status: "in-progress", isLegal: false },
  { id: "registry", title: "Uložit účetní závěrku do sbírky listin", description: "Nejzazší lhůta je obecně 12 měsíců od rozvahového dne.", category: "Obchodní rejstřík", deadline: "Do 12 měsíců od rozvahového dne", severity: "critical", status: "open", source: "Veřejné rejstříky", isLegal: true },
  { id: "registry-changes", title: "Zkontrolovat změny údajů v obchodním rejstříku", description: "Jednatelé, sídlo a další údaje mohou vyžadovat podání návrhu na změnu.", category: "Obchodní rejstřík", deadline: "Při každé změně", severity: "important", status: "open", source: "Veřejné rejstříky", isLegal: true },
  { id: "contracts", title: "Hlídání nájmů a dalších důležitých smluv", description: "Pohlídat výpovědi, automatická prodloužení, indexace a závazky.", category: "Smlouvy", deadline: "Měsíční kontrola", severity: "important", status: "open", isLegal: false },
  { id: "insurance", title: "Hlídání firemního pojištění", description: "Ověřit platnost smluv a rozsah krytí při růstu firmy nebo změně činnosti.", category: "Smlouvy", deadline: "Před výročním obnovením", severity: "routine", status: "open", isLegal: false },
  { id: "outgoing-invoices", title: "Zkontrolovat nezaplacené vydané faktury", description: "Pravidelně projít splatnost a poslat upomínky odběratelům.", category: "Banka a cashflow", deadline: "Každý týden", severity: "important", status: "open", isLegal: false },
  { id: "pay-invoices", title: "Zaplatit faktury před splatností", description: "Udržovat přehled o odchozích platbách a plánovaném cashflow.", category: "Banka a cashflow", deadline: "Každý týden", severity: "important", status: "in-progress", isLegal: false },
  { id: "bank-access", title: "Zkontrolovat oprávnění k bankovnímu účtu", description: "Odebrat staré přístupy a nastavit schvalování plateb podle rolí.", category: "Banka a cashflow", deadline: "Čtvrtletně", severity: "critical", status: "open", isLegal: false },
  { id: "gdpr", title: "Projít GDPR dokumentaci a zpracovatele", description: "Zkontrolovat zásady, souhlasy a smlouvy se zpracovateli osobních údajů.", category: "GDPR a data", deadline: "Při změně nástrojů nebo procesů", severity: "important", status: "open", source: "ÚOOÚ", isLegal: true },
  { id: "backups", title: "Zkontrolovat zálohy firemních dat", description: "Ověřit automatické zálohování a jednou za čas provést test obnovy.", category: "IT a bezpečnost", deadline: "Každý měsíc", severity: "critical", status: "open", isLegal: false },
  { id: "former-access", title: "Zkontrolovat přístupy bývalých zaměstnanců a spolupracovníků", description: "E-mail, cloud, repozitáře, VPN, účetní a fakturační nástroje.", category: "IT a bezpečnost", deadline: "Při ukončení spolupráce", severity: "critical", status: "open", isLegal: false },
  { id: "main-domain", title: "Expirace hlavní firemní domény", description: "Zapnout automatické prodloužení a hlídat kontaktní e-mail registrátora.", category: "Domény a předplatná", deadline: "Obnova za 31 dní", severity: "critical", status: "open", isLegal: false },
  { id: "saas", title: "Obnova důležitých SaaS předplatných", description: "Projít licence, vlastníky účtů a automatické obnovování služeb.", category: "Domény a předplatná", deadline: "Měsíční kontrola", severity: "routine", status: "open", isLegal: false },
  { id: "car-stk", title: "STK firemního auta", description: "Zkontrolovat termín technické kontroly a připravit doklady k vozidlu.", category: "Firemní auta a majetek", deadline: "Obnova za 74 dní", severity: "important", status: "open", isLegal: false },
  { id: "car-insurance", title: "Pojištění firemního auta", description: "Pohlídat povinné ručení, havarijní pojištění a platbu pojistného.", category: "Firemní auta a majetek", deadline: "Obnova za 89 dní", severity: "important", status: "open", isLegal: false },
];
