export type ItemCategory = "Založení firmy" | "Účetnictví" | "Daně" | "DPH" | "Datová schránka" | "Úřady" | "Zaměstnanci" | "Obchodní rejstřík" | "Smlouvy" | "Banka a cashflow" | "GDPR a data" | "IT a bezpečnost" | "Domény a předplatná" | "Firemní auta a majetek";
export type ItemSeverity = "urgent" | "important" | "routine";
export type CompanyItem = { id: string; title: string; description: string; category: ItemCategory; deadline: string; severity: ItemSeverity; status: "open" | "done"; kind: "legal" | "reminder"; source?: string };
const ITEM = (id: string, title: string, description: string, category: ItemCategory, deadline: string, severity: ItemSeverity, kind: CompanyItem["kind"] = "reminder", source?: string): CompanyItem => ({ id, title, description, category, deadline, severity, status: "open", kind, source });
export const COMPANY_ITEMS: CompanyItem[] = [
ITEM("tax-registration", "Přihlásit s.r.o. k dani z příjmů právnických osob", "Do 15 dnů od vzniku společnosti. Ověřit také další registrační povinnosti.", "Daně", "Do 15 dnů od vzniku", "urgent", "legal", "Finanční správa"),
ITEM("databox", "Zkontrolovat, že má firma funkční datovou schránku", "Přihlášení a přístupové údaje musí mít bezpečně uložené alespoň jednatel.", "Datová schránka", "Ověřit při založení", "important", "legal", "mojedatovaschranka.cz"),
ITEM("databox-alerts", "Nastavit notifikace z datové schránky", "Zapnout e-mailová upozornění a určit, kdo schránku pravidelně kontroluje.", "Datová schránka", "Při založení · jednorázově", "important"),
ITEM("databox-delivery", "Pohlídat fikci doručení datové zprávy", "Nepřečtená datová zpráva může být po 10 dnech považována za doručenou.", "Datová schránka", "Průběžně · každý pracovní den", "urgent", "legal", "zákon č. 300/2008 Sb."),
ITEM("accounting", "Nastavit účetnictví a předávání dokladů účetní", "Domluvit termín uzávěrky, formát dokladů a odpovědnost za jejich kontrolu.", "Účetnictví", "Při startu · jednorázově", "important"),
ITEM("monthly-documents", "Odevzdat účetní všechny doklady za minulý měsíc", "Faktury, účtenky, bankovní výpisy a další podklady předat v dohodnutém termínu.", "Účetnictví", "Každý měsíc · do 10. dne", "important"),
ITEM("corporate-tax-return", "Podat daňové přiznání k dani z příjmů právnických osob", "Standardně 3 měsíce, při pozdějším elektronickém podání 4 měsíce nebo 6 měsíců v zákonem stanovených případech.", "Daně", "Ročně · podle lhůty", "urgent", "legal", "Finanční správa"),
ITEM("tax-payment", "Zaplatit vypočtenou daň", "Pohlídat platbu podle podaného přiznání a správný variabilní symbol.", "Daně", "Ročně · při podání přiznání", "urgent", "legal"),
ITEM("closing", "Připravit účetní závěrku", "Zajistit inventarizaci, schválení závěrky a podklady pro daňové přiznání.", "Účetnictví", "Ročně · po skončení roku", "important", "legal"),
ITEM("collection", "Uložit účetní závěrku do sbírky listin", "Nejzazší lhůta je obecně 12 měsíců od rozvahového dne.", "Obchodní rejstřík", "Do 12 měsíců od rozvahového dne", "important", "legal", "justice.cz"),
ITEM("vat-foreign", "Nákupy zahraničních služeb: prověřit identifikovanou osobu", "OpenAI, Google, Meta, AWS, Figma nebo jiná služba ze zahraničí může založit povinnost k DPH.", "DPH", "Při každém nákupu ze zahraničí", "urgent", "legal", "Finanční správa"),
ITEM("vat-identified", "Při vzniku postavení identifikované osoby hlídat registraci", "Přihlášku podat do 15 dnů od rozhodné skutečnosti.", "DPH", "Do 15 dnů od rozhodné skutečnosti", "urgent", "legal"),
ITEM("vat-turnover", "Hlídání obratu pro povinnou registraci k DPH", "Počítat obrat za kalendářní rok a sledovat hranice 2 000 000 Kč a 2 536 500 Kč.", "DPH", "Průběžně · každý měsíc", "important", "legal"),
ITEM("vat-deadline", "Po překročení hranice hlídat přihlášku k DPH", "Po překročení relevantní hranice běží lhůta 10 pracovních dnů pro přihlášku k registraci plátce DPH.", "DPH", "Do 10 pracovních dnů", "urgent", "legal"),
ITEM("invoices-payable", "Zaplatit faktury před splatností", "Pravidelně projít závazky a naplánovat platby s rezervou.", "Banka a cashflow", "Týdně · před splatností", "important"),
ITEM("invoices-issued", "Zkontrolovat nezaplacené vydané faktury", "Pohlídat inkaso, upomínky a dopad na cashflow.", "Banka a cashflow", "Týdně · každý pátek", "important"),
ITEM("company-register", "Zkontrolovat změny údajů v obchodním rejstříku", "Změna jednatelů, sídla nebo dalších údajů může vyžadovat návrh na zápis.", "Obchodní rejstřík", "Při každé změně", "important", "legal"),
ITEM("first-employee", "Ověřit povinnosti před přijetím prvního zaměstnance", "Prověřit registrace, pracovněprávní dokumentaci, BOZP a pracovnělékařské služby.", "Zaměstnanci", "Před prvním nástupem", "urgent", "legal"),
ITEM("payroll", "Nastavit mzdovou agendu při přijetí prvního zaměstnance", "Domluvit zpracování mezd, výplatní termín a předávání podkladů.", "Zaměstnanci", "Před prvním nástupem", "important"),
ITEM("probation", "Hlídání pracovních smluv a konců zkušebních dob", "Udržovat přehled smluv, dodatků, dovolených a termínů hodnocení.", "Zaměstnanci", "Měsíčně · zkontrolovat", "routine"),
ITEM("contracts", "Hlídání nájmů a dalších důležitých smluv", "Zapsat výpovědní lhůty, automatická prodloužení a povinnosti obou stran.", "Smlouvy", "Měsíčně · přehled smluv", "important"),
ITEM("insurance", "Hlídání firemního pojištění", "Ověřit platnost pojistných smluv, limity a termíny obnovy.", "Smlouvy", "Čtvrtletně · zkontrolovat", "important"),
ITEM("domain", "Expirace hlavní firemní domény", "Zkontrolovat automatické prodloužení a platební kartu registrátora.", "Domény a předplatná", "Ročně · 30 dní před expirací", "urgent"),
ITEM("domains", "Expirace dalších domén", "Udržovat seznam všech domén a vlastníků účtů u registrátora.", "Domény a předplatná", "Ročně · 30 dní před expirací", "important"),
ITEM("ssl", "Obnova SSL certifikátů", "Ověřit certifikáty, pokud nejsou obnovované automaticky.", "IT a bezpečnost", "Měsíčně · ověřit", "important"),
ITEM("saas", "Obnova důležitých SaaS předplatných", "Projít licence a zrušit služby, které firma nepoužívá.", "Domény a předplatná", "Měsíčně · kontrola", "routine"),
ITEM("backups", "Zkontrolovat zálohy firemních dat", "Ověřit, že zálohy probíhají a lze z nich data skutečně obnovit.", "GDPR a data", "Měsíčně · test obnovy", "urgent"),
ITEM("access", "Zkontrolovat přístupy bývalých zaměstnanců a spolupracovníků", "Odebrat účty, tokeny, sdílené odkazy a přístupy do nástrojů.", "IT a bezpečnost", "Při odchodu · do 24 hodin", "urgent"),
ITEM("bank-access", "Zkontrolovat oprávnění k bankovnímu účtu", "Ověřit podpisová oprávnění, limity a aktivní uživatele internetového bankovnictví.", "Banka a cashflow", "Čtvrtletně · kontrola", "important"),
ITEM("car-inspection", "STK firemního auta", "Zapsat termín technické kontroly a připomínku s dostatečným předstihem.", "Firemní auta a majetek", "Podle techničáku · 30 dní předem", "important"),
ITEM("car-insurance", "Pojištění firemního auta", "Pohlídat povinné ručení, havarijní pojištění a termín obnovy.", "Firemní auta a majetek", "Ročně · před obnovou", "important"),
ITEM("gdpr", "Projít zpracování osobních údajů", "Udržovat přehled účelů, zpracovatelů, retenčních lhůt a přístupů k osobním údajům.", "GDPR a data", "Pololetně · kontrola", "important", "legal"),
ITEM("trade-license", "Ověřit platnost živnostenských oprávnění", "Před novou činností ověřit, že ji pokrývá předmět podnikání a oprávnění.", "Úřady", "Při rozšíření činnosti", "important", "legal"),
ITEM("founding", "Uložit zakladatelské dokumenty a přístupy", "Mít bezpečně uloženou společenskou smlouvu, výpisy a klíčové firemní dokumenty.", "Založení firmy", "Při založení · jednorázově", "routine")];
